Repository INHATC-EUNHATHON-TEAM6/BE, pull requests merged in 2025-08, with the labels that each got.

#5 ✨ feat: Implement SignupService with user registration logicSignup service
  src/main/java/com/hdd/config/SecurityConfig.java
  src/main/java/com/hdd/dto/SignupRequestDto.java
  src/main/java/com/hdd/reopository/UserRepository.java
  src/main/java/com/hdd/repository/UserRepository.java
  src/main/java/com/hdd/service/SignupService.java
Labels: 🟠 Priority : High

#7 ✨ Add integration tests for signup feature
  build.gradle
  src/main/java/com/hdd/dto/SignupRequestDto.java
  src/main/java/com/hdd/service/SignupService.java
  src/main/resources/application.properties
  src/test/java/com/hdd/integration/SignupIntegrationTest.java
  src/test/java/com/hdd/service/SignupServiceTest.java
Labels: 🔴 Priority : Very High

#21 Revert "Feature/crawling"
  .gitignore
  build.gradle
  src/main/java/com/backend/words_hanjoom/WordsHanjoomApplication.java
  src/main/java/com/words_hanjoom/TestController.java
  src/main/java/com/words_hanjoom/WordsHanjoomApplication.java
  src/main/java/com/words_hanjoom/domain/crawling/controller/CrawlController.java
  src/main/java/com/words_hanjoom/domain/crawling/dto/request/CrawlRequest.java
  src/main/java/com/words_hanjoom/domain/crawling/dto/request/SectionRequest.java
  src/main/java/com/words_hanjoom/domain/crawling/dto/response/ArticleResponse.java
  src/main/java/com/words_hanjoom/domain/crawling/dto/response/CrawlResult.java
  src/main/java/com/words_hanjoom/domain/crawling/entity/Article.java
  src/main/java/com/words_hanjoom/domain/crawling/entity/CrawlCategory.java
  src/main/java/com/words_hanjoom/domain/crawling/exception/CrawlException.java
  src/main/java/com/words_hanjoom/domain/crawling/repository/ArticleRepository.java
  src/main/java/com/words_hanjoom/domain/crawling/repository/CrawlCategoryRepository.java
  src/main/java/com/words_hanjoom/domain/crawling/repository/INewsContentCrawl.java
  src/main/java/com/words_hanjoom/domain/crawling/repository/IPageCounter.java
  src/main/java/com/words_hanjoom/domain/crawling/repository/IScraperService.java
  src/main/java/com/words_hanjoom/domain/crawling/repository/ISubCategoryCrawl.java
  src/main/java/com/words_hanjoom/domain/crawling/scheduler/CrawlScheduler.java
  src/main/java/com/words_hanjoom/domain/crawling/service/HKNewsCrawlService.java
  src/main/java/com/words_hanjoom/domain/crawling/service/HankyungScraperService.java
  src/main/java/com/words_hanjoom/domain/crawling/service/SCNewsCrawlService.java
  src/main/java/com/words_hanjoom/domain/crawling/service/ScienceTimesScraperService.java
  src/main/java/com/words_hanjoom/domain/users/controller/AuthController.java
  src/main/java/com/words_hanjoom/domain/users/controller/LoginController.java
  src/main/java/com/words_hanjoom/domain/users/dto/request/LoginUserRequestDto.java
  src/main/java/com/words_hanjoom/domain/users/dto/request/SignupRequestDto.java
  src/main/java/com/words_hanjoom/domain/users/dto/response/LoginUserResponseDto.java
  src/main/java/com/words_hanjoom/domain/users/entity/Category.java
  src/main/java/com/words_hanjoom/domain/users/entity/User.java
  src/main/java/com/words_hanjoom/domain/users/entity/UserCategory.java
  src/main/java/com/words_hanjoom/domain/users/entity/UserCategoryId.java
  src/main/java/com/words_hanjoom/domain/users/exception/GlobalExceptionHandler.java
  src/main/java/com/words_hanjoom/domain/users/repository/CategoryRepository.java
  src/main/java/com/words_hanjoom/domain/users/repository/LoginUserRepository.java
  src/main/java/com/words_hanjoom/domain/users/repository/UserCategoryRepository.java
  src/main/java/com/words_hanjoom/domain/users/repository/UserRepository.java
  src/main/java/com/words_hanjoom/domain/users/service/LoginService.java
  src/main/java/com/words_hanjoom/domain/users/service/SignupService.java
  src/main/java/com/words_hanjoom/global/config/SecurityConfig.java
  src/main/java/com/words_hanjoom/global/config/SwaggerConfig.java
  src/main/java/com/words_hanjoom/global/security/AuthenticationFilter.java
  src/main/java/com/words_hanjoom/global/security/TokenProvider.java
  src/main/java/com/words_hanjoom/global/util/HeaderUtil.java
  src/main/resources/application.properties
  src/test/java/com/backend/words_hanjoom/WordsHanjoomApplicationTests.java
  src/test/java/com/words_hanjoom/scheduler/SchedulerTest.java
Labels: 🔴 Priority : Very High, 🏃Feature

#14 [FEAT] 스크랩 활동 피드백 API
  .gitignore
  build.gradle
  src/main/java/com/words_hanjoom/WordsHanjoomApplication.java
  src/main/java/com/words_hanjoom/domain/feedback/controller/FeedbackController.java
  src/main/java/com/words_hanjoom/domain/feedback/dto/request/ScrapActivityDto.java
  src/main/java/com/words_hanjoom/domain/feedback/dto/response/FeedbackDto.java
  src/main/java/com/words_hanjoom/domain/feedback/dto/response/FeedbacksDto.java
  src/main/java/com/words_hanjoom/domain/feedback/entity/ActivityType.java
  src/main/java/com/words_hanjoom/domain/feedback/entity/Article.java
  src/main/java/com/words_hanjoom/domain/feedback/entity/Category.java
  src/main/java/com/words_hanjoom/domain/feedback/entity/ScrapActivities.java
  src/main/java/com/words_hanjoom/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/words_hanjoom/domain/feedback/repository/SpringDataJpaArticleRepository.java
  src/main/java/com/words_hanjoom/domain/feedback/repository/SpringDataJpaFeedbackRepository.java
  src/main/java/com/words_hanjoom/domain/feedback/service/CosineSimilarity.java
  src/main/java/com/words_hanjoom/domain/feedback/service/FeedbackService.java
  src/main/java/com/words_hanjoom/domain/feedback/service/FeedbackServicePromptTemplate.java
  src/main/java/com/words_hanjoom/domain/feedback/service/RougeCalculator.java
  src/main/java/com/words_hanjoom/domain/feedback/service/SetSimilarityCalculator.java
  src/main/resources/application.properties
Labels: 🔴 Priority : Very High, 🏃Feature, 🧩 Task

#17 [✨ FEAT] 특정 스크랩 활동 피드백 내용 조회 API 구현
  src/main/java/com/words_hanjoom/domain/feedback/controller/FeedbackController.java
  src/main/java/com/words_hanjoom/domain/feedback/dto/response/FeedbacksDto.java
  src/main/java/com/words_hanjoom/domain/feedback/entity/Article.java
  src/main/java/com/words_hanjoom/domain/feedback/entity/Category.java
  src/main/java/com/words_hanjoom/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/words_hanjoom/domain/feedback/repository/SpringDataJpaArticleRepository.java
  src/main/java/com/words_hanjoom/domain/feedback/repository/SpringDataJpaFeedbackRepository.java
  src/main/java/com/words_hanjoom/domain/feedback/service/FeedbackService.java
Labels: 🔴 Priority : Very High, 🏃Feature

#18 [✨ FEAT] 월별 스크랩 활동 기록 조회 API
  src/main/java/com/words_hanjoom/domain/feedback/controller/FeedbackController.java
  src/main/java/com/words_hanjoom/domain/feedback/dto/response/FeedbackThisMonthActivityDto.java
  src/main/java/com/words_hanjoom/domain/feedback/entity/Category.java
  src/main/java/com/words_hanjoom/domain/feedback/repository/FeedbackRepository.java
  src/main/java/com/words_hanjoom/domain/feedback/repository/SpringDataJpaCategoryRepository.java
  src/main/java/com/words_hanjoom/domain/feedback/repository/SpringDataJpaFeedbackRepository.java
  src/main/java/com/words_hanjoom/domain/feedback/service/FeedbackService.java
Labels: 🔴 Priority : Very High, 🏃Feature
